### ISSUE TITLE
Sometimes links do not show up well

### ISSUE THREAD

**Issue by nikitavoloboev** [BramVanRensbergen/Reddit-Revamped#2]
As can be seen below : 

![2016-12-08 at 06 04](https://cloud.githubusercontent.com/assets/6391776/20998164/45bd87a0-bd0c-11e6-9a03-80a1576c3bca.png)

Also certain subreddits don't really work fully well with this style like [videos subreddit](https://www.reddit.com/r/videos/) : 

![2016-12-08 at 06 05](https://cloud.githubusercontent.com/assets/6391776/20998187/720bfb5c-bd0c-11e6-8316-dde075d33175.png)

I really love this theme. Thank you for making it.

**Comment by BramVanRensbergen** [comment]
Hi Nikita,

I think both of your issues are related to the use of subreddit styles 
-- they clash with almost all user styles (except for styles that make 
only minor changes). You'll have to disable subreddit styles,  you can 
do this in your reddit settings (disable "allow subreddits to show me 
custom themes").

If this did not fix your issue or if you have other suggestions or 
remarks, let me know!

Regards,
Bram
